{% set name = "protoc-gen-validate" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/protoc-gen-validate-{{ version }}.tar.gz
  sha256: a733b368e0415102c3298ba7720838093382ab835120e875837db2e34457f9a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel >=0.38.1
    - pip
  run:
    - python >=3.6z
    - validate_email >=1.3
    - jinja2 >=2.11.1
    - protobuf >=3.6.1
    - astunparse >=1.6.3

test:
  imports:
    - protoc_gen_validate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bufbuild/protoc-gen-validate
  summary: PGV for python via just-in-time code generation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ggirelli
