{% set name = "protoc-gen-validate" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 76c1cea6c2b1290fc2a266b7d19f44cdcc1dc496236b760db1a50e1672d6c978

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel >=0.38.1
    - pip
  run:
    - python >=3.6z
    - validate_email >=1.3
    - jinja2 >=2.11.1
    - protobuf >=3.6.1
    - astunparse >=1.6.3

test:
  imports:
    - protoc_gen_validate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bufbuild/protoc-gen-validate
  summary: PGV for python via just-in-time code generation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ggirelli
